version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: stt_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 123
  #  ports:
  #    - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ./DocumentRoot/:/var/www/html/
    ports:
      - "80:80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: devuser
      PMA_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "81:80"
    volumes:
      - /sessions
  #    - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  #  stdin_open: true
  #  tty: true
