version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: stt_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 123
  #  ports:
  #    - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ./DocumentRoot/:/var/www/html/
    ports:
      - "80:80"
