version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: stt_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 123
  #  ports:
  #    - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ../src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php-docker.ini
    #ports:
    #  - "80:80"
